---
- name: Deploy Docker Application
  hosts: terraform_servers
  become: yes

  vars:
    aws_region: eu-north-1
    aws_account_id: "057981665363"
    ecr_repository: terraform-devops-ecr
    image_tag: latest

  tasks:

    - name: Login to Amazon ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | \
        docker login --username AWS --password-stdin \
        {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com

    - name: Pull latest Docker image
      shell: |
        docker pull {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repository }}:{{ image_tag }}

    - name: Stop old container
      shell: docker stop tasksphere-container
      ignore_errors: yes

    - name: Remove old container
      shell: docker rm tasksphere-container
      ignore_errors: yes

    - name: Run latest container
      shell: |
        docker run -d \
          --name tasksphere-container \
          --restart unless-stopped \
          -p 8080:8080 \
          {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repository }}:{{ image_tag }}

    - name: Show running container
      shell: docker ps
      register: container_status

    - debug:
        var: container_status.stdout_lines